### ISSUE TITLE
Validation error when creating subaccount in Java

### ISSUE THREAD

**Issue by nicofuccella** [Blockstream/gdk#131]
I'm trying to use the `create_subaccount` method from Java wrapper. This is the JSON I'm trying to use:
```
{ name: "test", type: “2of2” }
```
Unfortunately I get `[Error: [json.exception.type_error.302] type must be number, but is object]` during the execution. I tried to use a number like `0` or `1` for `type` and I get this error: `[Error: [json.exception.type_error.302] type must be string, but is number]`. 
What is a valid value for `type`?

**Comment by LeoComandini** [comment]
As discussed privately, if you are using electrum based network, admissible types are:
- `p2sh-p2wpkh`
- `p2wpkh`
- `p2pkh`

And changing the type to one of those fixes the issue.

Still the error is not nice and must be improved.
That should be addressed in an upcoming change.
