### ISSUE TITLE
GA_disconnect does not stop session

### ISSUE THREAD

**Issue by pavel-kokolemin** [Blockstream/gdk#155]
`GA_disconnect` does not stop non-electrum network sessions.
To reproduce call:
```
    GA_create_session
    GA_set_notification_handler
    GA_connect
    GA_login_user
    GA_disconnect
    GA_destroy_session
```
Result:
Network notifications are still received after `GA_disconnect` and `GA_destroy_session` calls (for example when you stop and restart internet connection).

The session is stopped with this change in `session::disconnect`:
```
-            if (p && p->get_network_parameters().is_electrum()) {
+            if (p) {
                 GDK_LOG_SEV(log_level::debug) << "session is something and we are in electrum. Disconnect";
                 p->disconnect();
             }
```
But helper boost threads are not stopped after that and so it's not a proper fix.
I'm attaching small program that could reproduce the bug.
[gdk_test.zip](https://github.com/Blockstream/gdk/files/7788159/gdk_test.zip)

**Comment by LeoComandini** [comment]
Hi @pavel-kokolemin 

Sorry for the late reply.

I replicated your error with your example.
However I noticed that you are reusing the `GA_auth_handler` across calls.
The [documentation](https://gdk.readthedocs.io/en/release_0.0.48/gdk/#c.GA_login_user) says that "Returned `GA_auth_handler` should be freed using `GA_destroy_auth_handler`."
Creating a new `GA_auth_handler` for each call and calling `GA_destroy_auth_handler` after solves the issues on my side (GDK correctly unsubscribes and I don't receive notifications after `GA_destroy_session`).
Please let me know if that solves the issue for you as well.

**Comment by pavel-kokolemin** [comment]
Works great after adding `GA_destroy_auth_handler`, thanks!
