### ISSUE TITLE
Upgrade NDK to supported version

### ISSUE THREAD

**Issue by emanuelb** [Blockstream/gdk#162]
https://github.com/Blockstream/gdk/blob/5783e36e0fe4576819838bb357394504fa92e564/tools/bullseye_deps.sh#L12

The recommended version is r21 which is old, list of supported ndk versions are:
Latest LTS Version: r23b
Latest: r24
https://developer.android.google.cn/ndk/downloads?hl=en

Related issue in green android app: https://github.com/Blockstream/green_android/issues/138 which recommend using ndk r19b

**Comment by jgriffiths** [comment]
master is now updated to build with r23b, its also been tested here with r24 and works fine too.

Thanks for reporting this @emanuelb !
