### ISSUE TITLE
android restore mnemonic error

### ISSUE THREAD

**Issue by mattiaferrari02** [Blockstream/gdk#165]
On android the validate mnemonic function gives always ` GDK_ERROR_CODE -1 ` with the method GA_validate_mnmemonic. This error occurs while passing a valid mnemonic or a wrong one

GDK version 0.0.54

**Comment by tiero** [comment]
Is this still happening?

**Comment by jgriffiths** [comment]
Sorry, we updated the release notes when we fixed this but didn't close this issue, thanks for catching it!
