### ISSUE TITLE
`encrypt_with_pin` raises a RuntimeError

### ISSUE THREAD

**Issue by louisinger** [Blockstream/gdk#172]
Using python-swig gdk 0.55 (.whl [file](https://github.com/Blockstream/gdk/releases/download/release_0.0.55/greenaddress-0.0.55-cp39-cp39-linux_x86_64.whl)), the following code:

```python
pin_data = session.encrypt_with_pin({ 'pin': '1234', 'plaintext': { 'mnemonic': 'word word word word'} }).resolve()
```
raises a RuntimeError: `RuntimeError: assertion failure: ../src/session_impl.cpp:get_nonnull_signer:392:`

**Comment by jgriffiths** [comment]
Thanks for reporting, FYI we are working on this now.

**Comment by louisinger** [comment]
need login_user call first to use `encrypt_with_pin`.
