### ISSUE TITLE
GDK 0.0.62 (and earlier) rejected by Google PlayStore due to 'defective' openssl version

### ISSUE THREAD

**Issue by opacey** [Blockstream/gdk#193]
Hi GDK team, we are using GDK as part of an Android app for its wallet functions in a custom Elements chain.

After a few years of smooth submissions and publications, Google are rejected our latest submissions with the attached complaint that the .apk includes an unstable version of openssl.

The original complaint was based on a very old GDK library (not sure which version but from 2 or 3 years ago)
We updated to 0.0.53 which states "Update openssl to 1.1.1n", but received the same rejection response
We updated to 0.0.62 but again received the same rejection response.

I am assured by the main developer that we are not linked to openssl in any other parts of the application (I cannot be 100% confident of this though)

Has anyone else experienced this issue?
Do the PlayStore team automate all of these checks or is it possible there is wide scope for human error and they are testing an old submission?
Any help would be appreciated.
![2023-05-17 17 11 28](https://github.com/Blockstream/gdk/assets/13622471/095951fb-92b8-43f9-af87-1d68749e3d3a)

**Comment by jgriffiths** [comment]
Hi,

you can determine the compiled in openssl version using:

```
$ strings libgreenaddress.so | fgrep '1.1.1'
OpenSSL 1.1.1n  15 Mar 2022
OpenSSL 1.1.1n  15 Mar 2022
...
```

(This example on gdk 0.62). In the event that your build has somehow included openssl non-statically, run `ldd` on the `.so` file and see if openssl libs are listed as being dynamically linked. If this is happening it could be the case that the test expects either static linking or a newer openssl to be shipped with your app (for devices with insecure versions).

If neither of these offer any clues you will probably need to reach out to google to find the specifics of their tests. The Green wallets do not appear to be affected by this check.

**Comment by jgriffiths** [comment]
@opacey update: it seems that Google wants version 1.1.1t. We are testing an update to that version and will merge it to master shortly.

If you take that change, you will want to backport it to 0.62 rather than running the master which is not suitable for releasing from just yet.

**Comment by opacey** [comment]
ah amazing, thank you @jgriffiths , that's invaluable research and info - thanks also for prioritising the update. Will watch out for it and try the backport. I'll report back here if nay success or problems.

**Comment by jgriffiths** [comment]
@opacey gdk master is now updated with the latest openssl.

**Comment by opacey** [comment]
Look like you've already done the work @jgriffiths! Shall we try with 0.062 and back port your commitments fro the last few hours to it?

![image](https://github.com/Blockstream/gdk/assets/13622471/6073f10e-5e57-46ca-b4b6-339407cbd74d)

**Comment by jgriffiths** [comment]
> am I right in thinking the only one I need to apply

@opacey yes, that single commit is enough. We will be releasing a new gdk version shortly (this week) based on current master.

**Comment by opacey** [comment]
Hi @jgriffiths do you think the 0.0.63 release is on track for this week?
Also, do you know if there are plans to upgrade GDK to openssl 3.x? apparently the 1.1.1 LT series expires in Sept '23.

**Comment by jgriffiths** [comment]
Hi @opacey we are testing the candidate release (master) now. I have one bug fix I'm about to submit and one other minor issue to investigate. Unless we find some other issues during testing, everything looks on track for a release on Friday. If there is a delay, it will most likely be Monday.

**Comment by jgriffiths** [comment]
>plans to upgrade GDK to openssl 3.x

This is on our radar but not currently prioritized.

**Comment by opacey** [comment]
Thanks kindly for the updates @jgriffiths !

**Comment by opacey** [comment]
Excited to see the 0.0.63 release https://github.com/Blockstream/gdk/releases/tag/release_0.0.63 however its marked pre-release. How long is the finalised release of 0.0.63 likely to take (roughly)? If its this week we will wait for it, if its longer we will risk the pre-releaase but could you give us a qualitative idea of the risk we'd be taking?

**Comment by jgriffiths** [comment]
Hi @opacey The release was delayed slightly by the American long weekend, apologies for that. We generally release gdk initially as a pre-release just for acceptance testing of the final built artifacts, this is complete now so the release is final.

Please let us know if you encounter any issues and don't forget to account for the CHANGELOG.md changes in 0.63.

**Comment by jgriffiths** [comment]
Hi @opacey Looks like our tor version is affected, I will fix this in gdk master.

**Comment by opacey** [comment]
Fantastic, thanks kindly @jgriffiths!

**Comment by jgriffiths** [comment]
@opacey https://github.com/Blockstream/gdk/tree/playstore_tor_fix contains the fix, this will be merged to master shortly following our internal review and CI process.

I expect we will make a new gdk release in a couple of weeks with this change if you need an official release to work from.

**Comment by jgriffiths** [comment]
Merged to master, please re-open if this fix doesn't work for you, thanks.
