### ISSUE TITLE
Liquid xpubs

### ISSUE THREAD

**Issue by kilrau** [Blockstream/gdk#201]
GDK should natively allow creating and exporting liquid xpubs. Some test vectors are already specified in https://github.com/ElementsProject/ELIPs/blob/main/elip-0150.mediawiki#test-vectors and https://github.com/ElementsProject/elements-miniscript seems to have added xpubs recently too.

**Comment by LeoComandini** [comment]
We're planning to add support for it, but we need a elements-miniscript release first.
I think this will likely be early next year.

See https://github.com/Blockstream/gdk/tree/2023-09-25-liquid-watch-only for the ongoing work

**Comment by LeoComandini** [comment]
Hi @kilrau ,

The branch above is ready to be merged, and it should be merged soon.

Here are some test vectors:

---

* mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
* network: liquid __mainnet__
* account type: __p2sh-p2wpkh__
* external descriptor (receive): `"ct(slip77(9c8e4f05c7711a98c838be228bcb84924d4570ca53f35fa1c793e58841d47023),elsh(wpkh([73c5da0a/49'/1776'/0']xpub6BemYiVNp19a21wSJsQXGYzkD75QmrspVUAhdyzwMEAA3dKkgck5D3S9k7ymKZfGBbSAaQUHZ1qGa2TRKFHPjaYyc4fjMVjVweexRajeuNu/0/*)))#ln0mhncc"`
* internal descriptor (change): `"ct(slip77(9c8e4f05c7711a98c838be228bcb84924d4570ca53f35fa1c793e58841d47023),elsh(wpkh([73c5da0a/49'/1776'/0']xpub6BemYiVNp19a21wSJsQXGYzkD75QmrspVUAhdyzwMEAA3dKkgck5D3S9k7ymKZfGBbSAaQUHZ1qGa2TRKFHPjaYyc4fjMVjVweexRajeuNu/1/*)))#04928rdp"`

---

* mnemonic: "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
* network: liquid __testnet__
* account type: __p2wpkh__
* external descriptor (receive): `"ct(slip77(9c8e4f05c7711a98c838be228bcb84924d4570ca53f35fa1c793e58841d47023),elwpkh([73c5da0a/84'/1'/0']tpubDC2Q4xK4XH72GXm29HWiRTpMjjpyjDXCHaCMPbJWDKBVTDfHEkbHNrLJYEZdmth48FDXeX3jwWQ5WTMh5sXUA8bWDn3xEj1GdqjLyBpXGSA/0/*))#srqdk7w4"`
* internal descriptor (change): `"ct(slip77(9c8e4f05c7711a98c838be228bcb84924d4570ca53f35fa1c793e58841d47023),elwpkh([73c5da0a/84'/1'/0']tpubDC2Q4xK4XH72GXm29HWiRTpMjjpyjDXCHaCMPbJWDKBVTDfHEkbHNrLJYEZdmth48FDXeX3jwWQ5WTMh5sXUA8bWDn3xEj1GdqjLyBpXGSA/1/*))#9zwmwpm2"`

**Comment by jackstar12** [comment]
@LeoComandini works as expected.

**Comment by hsdredgun** [comment]
WOWO this is such a good news. Can't wait to be able to receive liquid fund without Jade connected!

**Comment by kilrau** [comment]
What is missing here?

**Comment by LeoComandini** [comment]
@kilrau nothing, all merged

**Comment by kilrau** [comment]
Goodie
