### ISSUE TITLE
show proper error when change is below dust threshold

### ISSUE THREAD

**Issue by jackstar12** [Blockstream/gdk#213]
Currently, an `Insufficient funds for fees` error is thrown when the change amount is below dust threshold which is confusing to the user:
https://github.com/Blockstream/gdk/blob/c3a77be3068f2f4b9b984b93c3f3b5ce5befd6a4/src/ga_tx.cpp#L566

If this condition is true and no more utxos are available, a proper error should be thrown:
https://github.com/Blockstream/gdk/blob/c3a77be3068f2f4b9b984b93c3f3b5ce5befd6a4/src/ga_tx.cpp#L535

E.g. `Change is below dust threshold`

**Comment by jgriffiths** [comment]
Fixed in release https://github.com/Blockstream/gdk/releases/tag/release_0.73.4
