### ISSUE TITLE
Fiat exchange rate source 

### ISSUE THREAD

**Issue by FrancisPouliot** [Blockstream/gdk#24]
Where can we add the exchange rate sources API?

Would like to add the Bull Bitcoin $CAD price API.

**Comment by greenaddress** [comment]
For two+ reasons the rate api is handled server side: 

- to avoid spamming the api providers from the mobiles

- because we also have the fiat data in out of band 2fa messages or fiat limits enforcement

We can add the cad source to the backend and it will be available to all apps

**Comment by jgriffiths** [comment]
Bull bitcoin has been aded for a while now, closing.
